services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile

    working_dir: /var/www/src

    command: ['php', '-S', '0.0.0.0:8889']

    environment:
      - LOCAL_PHP_XDEBUG=${LOCAL_PHP_XDEBUG-false}
      - XDEBUG_MODE=${LOCAL_PHP_XDEBUG_MODE-develop,debug}
      - GITHUB_REF=${GITHUB_REF-false}
      - GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME-false}

    networks:
      - wpdevnet

    volumes:
      - ./docker/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./:/var/www

    ports:
      - "8889:8889"

  mysql:
    image: mysql/mysql-server:8.0

    networks:
      - wpdevnet

    ports:
      - "3306"

    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'

    volumes:
      - ./tools/local-env/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      - mysql:/var/lib/mysql

    command: --default-authentication-plugin=mysql_native_password

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      timeout: 5s
      interval: 5s
      retries: 10

  cli:
    build:
      context: .
      dockerfile: ./docker/Dockerfile

    profiles: ['cli']

    working_dir: /var/www

    entrypoint: ['/usr/local/bin/wp', '--allow-root']

    networks:
      - wpdevnet

    volumes:
      - ./docker/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
      - ./docker/xdebug.ini.disabled:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./:/var/www

volumes:
  mysql: ~

networks:
  wpdevnet: ~
