services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile

    command: [ 'wp', 'server', '--host=0.0.0.0', '--port=8889' ]

    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-develop}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-client_host=172.17.0.1}
      - GITHUB_REF=${GITHUB_REF-false}
      - GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME-false}

    networks:
      - wpdevnet

    volumes:
      - ./docker/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./:/var/www

    ports:
      - "${LOCAL_PORT-8889}:8889"

  mysql:
    image: mysql/mysql-server:8.0

    networks:
      - wpdevnet

    ports:
      - "${LOCAL_DB_PORT-33069}:3306"

    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'

    volumes:
      - ./tools/local-env/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      - mysql:/var/lib/mysql

    command: --default-authentication-plugin=mysql_native_password

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      timeout: 5s
      interval: 5s
      retries: 10

volumes:
  mysql: ~

networks:
  wpdevnet: ~
